repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-ast
      - id: check-json
      - id: detect-aws-credentials
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.0.1"
    hooks:
      - id: mypy
  - repo: https://github.com/PyCQA/bandit
    rev: "1.7.4"
    hooks:
      - id: bandit
        args: ["-q"]
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args: ["--fail-under=8"]
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.0.254"
    hooks:
      - id: ruff
  - repo: https://github.com/returntocorp/semgrep
    rev: 'v1.14.0'
    hooks:
      - id: semgrep
        args: ['--config', 'auto', '--error']
  - repo: https://github.com/bridgecrewio/checkov.git
    rev: '2.3.128'
    hooks:
      - id: checkov
  - repo: https://github.com/pypa/pip-audit
    rev: v2.5.4
    hooks:
      -   id: pip-audit
